#!/bin/bash
echo "$1" >concore.maxtime
echo "FROM alpine:3.8" > Dockerfile
sudo docker build -t docker-concore .
sudo docker run --name=concore -v 1_CU:/1_CU -v 2_PYM:/2_PYM docker-concore >/dev/null &
sleep 3
echo "copying concore.maxtime=$1"
sudo docker cp concore.maxtime concore:/1_CU/concore.maxtime
sudo docker cp concore.maxtime concore:/2_PYM/concore.maxtime
sudo docker stop concore 
sudo docker rm concore
sudo docker rmi docker-concore
rm Dockerfile
rm concore.maxtime
