#!/bin/bash
echo "$1" >concore.maxtime
echo "FROM alpine:3.8" > Dockerfile
docker build -t docker-concore .
docker run --name=concore -v 1_CU:/1_CU -v 2_PYM:/2_PYM docker-concore >/dev/null &
sleep 3
echo "copying concore.maxtime=$1"
docker cp concore.maxtime concore:/1_CU/concore.maxtime
docker cp concore.maxtime concore:/2_PYM/concore.maxtime
docker stop concore 
docker rm concore
docker rmi docker-concore
rm Dockerfile
rm concore.maxtime
