#!/bin/bash
echo "$1" >concore.maxtime
echo "FROM alpine:3.8" > Dockerfile
sudo docker build -t docker-concore .
sudo docker run --name=concore -v vol_Y2:/vol_Y2 -v vol_U:/vol_U -v vol_Y:/vol_Y -v vol_U2:/vol_U2 docker-concore >/dev/null &
sleep 3
echo "copying concore.maxtime=$1"
sudo docker cp concore.maxtime concore:/vol_Y2/concore.maxtime
sudo docker cp concore.maxtime concore:/vol_U/concore.maxtime
sudo docker cp concore.maxtime concore:/vol_Y/concore.maxtime
sudo docker cp concore.maxtime concore:/vol_U2/concore.maxtime
sudo docker stop concore 
sudo docker rm concore
sudo docker rmi docker-concore
rm Dockerfile
rm concore.maxtime
