#!/bin/bash
echo "FROM alpine:3.8" > Dockerfile
sudo docker build -t docker-concore .
sudo docker run --name=concore -v vol_Y2:/vol_Y2 -v vol_U:/vol_U -v vol_Y:/vol_Y -v vol_U2:/vol_U2 docker-concore >/dev/null &
sleep 1
echo "copying concore.apikey"
sudo docker cp ~/concore.apikey concore:/vol_Y2/concore.apikey
sudo docker cp ~/concore.apikey concore:/vol_U/concore.apikey
sudo docker cp ~/concore.apikey concore:/vol_Y/concore.apikey
sudo docker cp ~/concore.apikey concore:/vol_U2/concore.apikey
sudo docker stop concore 
sudo docker rm concore
sudo docker rmi docker-concore
rm Dockerfile
