#!/bin/bash
mkdir docker-pmpymax
cd docker-pmpymax
cp ../src/Dockerfile.pmpymax Dockerfile
cp ../src/pmpymax.jl .
cp -r ../src/Concore .
cp ../src/pmpymax.iport concore.iport
cp ../src/pmpymax.oport concore.oport
docker build -t docker-pmpymax .
cd ..
mkdir docker-cpymax
cd docker-cpymax
cp ../src/Dockerfile.cpymax Dockerfile
cp ../src/cpymax.jl .
cp -r ../src/Concore .
cp ../src/cpymax.iport concore.iport
cp ../src/cpymax.oport concore.oport
docker build -t docker-cpymax .
cd ..
mkdir docker-funcall
cd docker-funcall
cp ../src/Dockerfile.funcall Dockerfile
cp ../src/funcall.jl .
cp -r ../src/Concore .
cp ../src/funcall.iport concore.iport
cp ../src/funcall.oport concore.oport
cp -r ../src/funcall.dir/* .
docker build -t docker-funcall .
cd ..
mkdir docker-funbody
cd docker-funbody
cp ../src/Dockerfile.funbody Dockerfile
cp ../src/funbody.jl .
cp -r ../src/Concore .
cp ../src/funbody.iport concore.iport
cp ../src/funbody.oport concore.oport
cp -r ../src/funbody.dir/* .
docker build -t docker-funbody .
cd ..
